### ISSUE TITLE
Fix babel vulnerability

### ISSUE THREAD

**Issue by vprince1** [aws-solutions-library-samples/guidance-for-utility-bill-processing-on-aws#5]
A new "critical severity" vulnerability was identified recently for `@babel/traverse`. More details are in https://github.com/advisories/GHSA-67hx-6x53-jw92. Since your repository is using this package, kindly fix it at the earliest.

**Comment by guyu-ye** [comment]
fixed

**Comment by vprince1** [comment]
It looks like there are some typescript dependencies that are using the old version.
![image](https://github.com/aws-solutions-library-samples/guidance-for-utility-bill-processing-on-aws/assets/11996632/fa54d219-a000-4627-b159-e4822db32ba0)

**Comment by vprince1** [comment]
thanks for resolving
